name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.7', '3.8', '3.9' ] # currently no support for pytorch on py3.10

    steps:
      # checks-out repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # install python 3.9 (x64)
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      # we need pip and dependencies (see requirements.txt)
      - name: Install pip and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # cibuildwheel for multiplatform support
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.7.0

      # build wheels
      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: "pip install setuptools torch"
        run: python -m cibuildwheel --output-dir wheelhouse

      # upload
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
